apiVersion: v1
name: botika
version: 1.0.0
appVersion: 1.0.0
description: Chart for Botika Apache Tomcat Runtime
keywords:
  - tomcat
  - java
  - http
  - web
  - application server
  - jsp
engine: gotpl
icon: https://bitnami.com/assets/stacks/tomcat/img/tomcat-stack-110x117.png
